services:
  app:
    build: .
    volumes:
      - type: bind
        source: ./credentials.json
        target: /app/credentials.json
        read_only: true
      - type: bind
        source: ./config.ini
        target: /app/config.ini
        read_only: true
      - type: bind
        source: ./private-key.pem
        target: /app/private-key.pem
        read_only: true