services:
  app:
    build: .
    volumes:
      - type: bind
        source: ./credentials.json
        target: /app/credentials.json
        read_only: true
      - type: bind
        source: ./config.ini
        target: /app/dcbot/config.ini
        read_only: true
      - type: bind
        source: ./private-key.pem
        target: /app/dcbot/private-key.pem
        read_only: true
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: